import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Sidebar } from "@/components/ui/sidebar";
import { Toaster } from "sonner";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 1. Terapkan variabel font ke tag <body> agar berlaku global.
        2. Pastikan tag <body> membungkus semua elemen di dalamnya.
      */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex min-h-screen bg-background">
          <Sidebar />
          <main className="flex-1 p-8 overflow-y-auto">
            <div className="mx-auto max-w-7xl">
              {children}
            </div>
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}